### ISSUE TITLE
Update of code for Latest Play 2.5 ?

### ISSUE THREAD

**Issue by fahimmahmoodmir** [alexgaribay/play-authentication#1]
Hi i tried implementing your code in my project i am using Play 2.5 so i having trouble in implementing @with annotation. As `F.Promise` is now deprecated and it also not throw `Throwable` in latest update. Any plan to update your code for latest version?

**Comment by alexgaribay** [comment]
Sorry but no. I have no intention of updating this repo since I haven't touched Play Framework in over 2 years.
